// utils/mockData.js
// Mock 数据集中存储，供全局使用

const MOCK_USER = {
  id: 'user_001',
  nickName: '小明同学',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user001',
};

const INITIAL_POSTS = [
  // ===== 运动类 =====
  {
    id: 'post_001',
    title: '周末羽毛球双打，缺一人',
    category: '运动',
    subCategory: '羽毛球',
    timeInfo: { mode: 'fixed', fixedTime: '2025-08-02T09:00:00.000Z' },
    address: '北京市朝阳区劲松体育馆',
    coords: { latitude: 39.8823, longitude: 116.4551 },
    maxCount: 4,
    currentCount: 3,
    author: { id: 'user_002', nickName: '羽球达人', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user002' },
    createdAt: 1753660800000,
    distance: 1.2,
  },
  {
    id: 'post_002',
    title: '每天早晨跑步，欢迎加入',
    category: '运动',
    subCategory: '跑步',
    timeInfo: { mode: 'range', days: 7 },
    address: '上海市浦东新区世纪公园',
    coords: { latitude: 31.2204, longitude: 121.5440 },
    maxCount: 6,
    currentCount: 2,
    author: { id: 'user_003', nickName: '晨跑小将', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user003' },
    createdAt: 1753574400000,
    distance: 3.5,
  },
  {
    id: 'post_003',
    title: '篮球5v5，缺两名前锋',
    category: '运动',
    subCategory: '篮球',
    timeInfo: { mode: 'fixed', fixedTime: '2025-08-03T14:00:00.000Z' },
    address: '广州市天河区天河体育中心',
    coords: { latitude: 23.1291, longitude: 113.3270 },
    maxCount: 10,
    currentCount: 8,
    author: { id: 'user_004', nickName: '篮球队长', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user004' },
    createdAt: 1753488000000,
    distance: 0.8,
  },
  {
    id: 'post_004',
    title: '瑜伽晨练，初学者友好',
    category: '运动',
    subCategory: '瑜伽',
    timeInfo: { mode: 'range', days: 14 },
    address: '成都市武侯区人民公园',
    coords: { latitude: 30.6598, longitude: 104.0633 },
    maxCount: 8,
    currentCount: 3,
    author: { id: 'user_005', nickName: '瑜伽老师', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user005' },
    createdAt: 1753401600000,
    distance: 2.1,
  },
  // ===== 娱乐类 =====
  {
    id: 'post_005',
    title: '桌游之夜，三国杀/狼人杀',
    category: '娱乐',
    subCategory: '桌游',
    timeInfo: { mode: 'fixed', fixedTime: '2025-08-01T19:00:00.000Z' },
    address: '北京市海淀区中关村桌游吧',
    coords: { latitude: 39.9842, longitude: 116.3160 },
    maxCount: 8,
    currentCount: 5,
    author: { id: 'user_006', nickName: '桌游爱好者', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user006' },
    createdAt: 1753315200000,
    distance: 4.3,
  },
  {
    id: 'post_006',
    title: '周末看电影，约伴同行',
    category: '娱乐',
    subCategory: '电影',
    timeInfo: { mode: 'fixed', fixedTime: '2025-08-02T15:30:00.000Z' },
    address: '上海市静安区万达影城',
    coords: { latitude: 31.2304, longitude: 121.4737 },
    maxCount: 4,
    currentCount: 1,
    author: { id: 'user_007', nickName: '影迷小花', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user007' },
    createdAt: 1753228800000,
    distance: 5.6,
  },
  {
    id: 'post_007',
    title: 'KTV 嗨唱，欢迎麦霸',
    category: '娱乐',
    subCategory: 'KTV',
    timeInfo: { mode: 'range', days: 3 },
    address: '深圳市南山区星聚会KTV',
    coords: { latitude: 22.5431, longitude: 113.9340 },
    maxCount: 10,
    currentCount: 6,
    author: { id: 'user_008', nickName: '麦霸王者', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user008' },
    createdAt: 1753142400000,
    distance: 1.9,
  },
  // ===== 学习类 =====
  {
    id: 'post_008',
    title: '英语口语练习小组，每周两次',
    category: '学习',
    subCategory: '英语',
    timeInfo: { mode: 'range', days: 30 },
    address: '北京市西城区图书馆自习室',
    coords: { latitude: 39.9163, longitude: 116.3683 },
    maxCount: 6,
    currentCount: 4,
    author: { id: 'user_009', nickName: '英语学霸', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user009' },
    createdAt: 1753056000000,
    distance: 6.2,
  },
  {
    id: 'post_009',
    title: '考研数学刷题，互相监督',
    category: '学习',
    subCategory: '考研',
    timeInfo: { mode: 'fixed', fixedTime: '2025-08-04T08:00:00.000Z' },
    address: '武汉市洪山区武汉大学图书馆',
    coords: { latitude: 30.5428, longitude: 114.3598 },
    maxCount: 4,
    currentCount: 2,
    author: { id: 'user_010', nickName: '考研战士', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user010' },
    createdAt: 1752969600000,
    distance: 8.7,
  },
  {
    id: 'post_010',
    title: '编程学习小组，Python 入门',
    category: '学习',
    subCategory: '编程',
    timeInfo: { mode: 'range', days: 21 },
    address: '杭州市西湖区浙江大学紫金港校区',
    coords: { latitude: 30.3082, longitude: 120.0862 },
    maxCount: 5,
    currentCount: 3,
    author: { id: 'user_011', nickName: '码农小白', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user011' },
    createdAt: 1752883200000,
    distance: 12.4,
  },
  // ===== 其他类 =====
  {
    id: 'post_011',
    title: '周末摄影采风，城市街拍',
    category: '其他',
    subCategory: '摄影',
    timeInfo: { mode: 'fixed', fixedTime: '2025-08-03T08:00:00.000Z' },
    address: '上海市黄浦区外滩',
    coords: { latitude: 31.2397, longitude: 121.4900 },
    maxCount: 6,
    currentCount: 4,
    author: { id: 'user_012', nickName: '摄影师阿杰', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user012' },
    createdAt: 1752796800000,
    distance: 7.1,
  },
  {
    id: 'post_012',
    title: '美食探店，寻找隐藏小馆子',
    category: '其他',
    subCategory: '美食',
    timeInfo: { mode: 'range', days: 5 },
    address: '广州市越秀区北京路美食街',
    coords: { latitude: 23.1281, longitude: 113.2644 },
    maxCount: 4,
    currentCount: 1,
    author: { id: 'user_013', nickName: '吃货本货', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user013' },
    createdAt: 1752710400000,
    distance: 9.3,
  },
];

const CHAT_ITEMS_INITIATED = [
  {
    id: 'post_001',
    title: '周末羽毛球双打，缺一人',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=post001',
    lastMessage: '好的，明天见！',
    lastTime: '10:30',
  },
  {
    id: 'post_008',
    title: '英语口语练习小组，每周两次',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=post008',
    lastMessage: '这周五还是老地方',
    lastTime: '昨天',
  },
  {
    id: 'post_011',
    title: '周末摄影采风，城市街拍',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=post011',
    lastMessage: '记得带备用电池',
    lastTime: '周一',
  },
];

const CHAT_ITEMS_JOINED = [
  {
    id: 'post_002',
    title: '每天早晨跑步，欢迎加入',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=post002',
    lastMessage: '明天6点出发，不见不散',
    lastTime: '09:15',
  },
  {
    id: 'post_005',
    title: '桌游之夜，三国杀/狼人杀',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=post005',
    lastMessage: '我带狼人杀牌来',
    lastTime: '昨天',
  },
  {
    id: 'post_009',
    title: '考研数学刷题，互相监督',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=post009',
    lastMessage: '今天刷了30道题，加油！',
    lastTime: '周二',
  },
];

const CHAT_MESSAGES = {
  post_001: [
    {
      id: 'msg_001_1',
      postId: 'post_001',
      sender: { id: 'user_002', nickName: '羽球达人', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user002' },
      content: '大家好，我是发起人，欢迎加入！',
      time: '09:00',
    },
    {
      id: 'msg_001_2',
      postId: 'post_001',
      sender: { id: 'user_014', nickName: '小李', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user014' },
      content: '我报名了，期待周末！',
      time: '09:05',
    },
    {
      id: 'msg_001_3',
      postId: 'post_001',
      sender: { id: 'user_001', nickName: '小明同学', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user001' },
      content: '我也来，带球拍了',
      time: '09:10',
    },
    {
      id: 'msg_001_4',
      postId: 'post_001',
      sender: { id: 'user_002', nickName: '羽球达人', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user002' },
      content: '场地已预订，劲松体育馆3号场',
      time: '09:20',
    },
    {
      id: 'msg_001_5',
      postId: 'post_001',
      sender: { id: 'user_014', nickName: '小李', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user014' },
      content: '好的，明天见！',
      time: '10:30',
    },
  ],
  post_002: [
    {
      id: 'msg_002_1',
      postId: 'post_002',
      sender: { id: 'user_003', nickName: '晨跑小将', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user003' },
      content: '欢迎大家加入晨跑群！每天早上6点世纪公园南门集合',
      time: '07:00',
    },
    {
      id: 'msg_002_2',
      postId: 'post_002',
      sender: { id: 'user_001', nickName: '小明同学', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user001' },
      content: '好的，我明天开始参加',
      time: '07:15',
    },
    {
      id: 'msg_002_3',
      postId: 'post_002',
      sender: { id: 'user_015', nickName: '跑步爱好者', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user015' },
      content: '请问跑多远？',
      time: '07:20',
    },
    {
      id: 'msg_002_4',
      postId: 'post_002',
      sender: { id: 'user_003', nickName: '晨跑小将', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user003' },
      content: '一般5公里，量力而行，不强制',
      time: '07:25',
    },
    {
      id: 'msg_002_5',
      postId: 'post_002',
      sender: { id: 'user_015', nickName: '跑步爱好者', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user015' },
      content: '明天6点出发，不见不散',
      time: '09:15',
    },
  ],
  post_005: [
    {
      id: 'msg_005_1',
      postId: 'post_005',
      sender: { id: 'user_006', nickName: '桌游爱好者', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user006' },
      content: '今晚桌游之夜，地点：中关村桌游吧，19:00开始',
      time: '12:00',
    },
    {
      id: 'msg_005_2',
      postId: 'post_005',
      sender: { id: 'user_016', nickName: '狼人杀高手', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user016' },
      content: '我带狼人杀牌来',
      time: '12:30',
    },
    {
      id: 'msg_005_3',
      postId: 'post_005',
      sender: { id: 'user_001', nickName: '小明同学', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user001' },
      content: '我第一次玩，大家多关照',
      time: '13:00',
    },
    {
      id: 'msg_005_4',
      postId: 'post_005',
      sender: { id: 'user_006', nickName: '桌游爱好者', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user006' },
      content: '没关系，新手友好，我们会教你',
      time: '13:05',
    },
    {
      id: 'msg_005_5',
      postId: 'post_005',
      sender: { id: 'user_016', nickName: '狼人杀高手', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user016' },
      content: '还有三国杀，看大家想玩什么',
      time: '14:00',
    },
    {
      id: 'msg_005_6',
      postId: 'post_005',
      sender: { id: 'user_001', nickName: '小明同学', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user001' },
      content: '我带狼人杀牌来',
      time: '昨天',
    },
  ],
  post_008: [
    {
      id: 'msg_008_1',
      postId: 'post_008',
      sender: { id: 'user_009', nickName: '英语学霸', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user009' },
      content: '欢迎加入英语口语练习小组！每周二、五晚上7点，西城图书馆',
      time: '周一 20:00',
    },
    {
      id: 'msg_008_2',
      postId: 'post_008',
      sender: { id: 'user_017', nickName: '英语小白', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user017' },
      content: '我英语不太好，可以参加吗？',
      time: '周一 20:15',
    },
    {
      id: 'msg_008_3',
      postId: 'post_008',
      sender: { id: 'user_009', nickName: '英语学霸', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user009' },
      content: '当然可以，我们就是互相练习，不分水平',
      time: '周一 20:20',
    },
    {
      id: 'msg_008_4',
      postId: 'post_008',
      sender: { id: 'user_001', nickName: '小明同学', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user001' },
      content: '这周五还是老地方',
      time: '昨天',
    },
    {
      id: 'msg_008_5',
      postId: 'post_008',
      sender: { id: 'user_017', nickName: '英语小白', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user017' },
      content: '收到，准时到！',
      time: '昨天',
    },
  ],
  post_009: [
    {
      id: 'msg_009_1',
      postId: 'post_009',
      sender: { id: 'user_010', nickName: '考研战士', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user010' },
      content: '大家好，一起备战考研数学！每天打卡，互相监督',
      time: '周一 08:00',
    },
    {
      id: 'msg_009_2',
      postId: 'post_009',
      sender: { id: 'user_001', nickName: '小明同学', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user001' },
      content: '好的，我今天刷了20道题',
      time: '周一 22:00',
    },
    {
      id: 'msg_009_3',
      postId: 'post_009',
      sender: { id: 'user_010', nickName: '考研战士', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user010' },
      content: '厉害！我刷了25道，明天继续',
      time: '周一 22:10',
    },
    {
      id: 'msg_009_4',
      postId: 'post_009',
      sender: { id: 'user_001', nickName: '小明同学', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user001' },
      content: '今天刷了30道题，加油！',
      time: '周二',
    },
    {
      id: 'msg_009_5',
      postId: 'post_009',
      sender: { id: 'user_010', nickName: '考研战士', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user010' },
      content: '冲冲冲，距离考研还有150天！',
      time: '周二',
    },
  ],
  post_011: [
    {
      id: 'msg_011_1',
      postId: 'post_011',
      sender: { id: 'user_012', nickName: '摄影师阿杰', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user012' },
      content: '周末外滩街拍，早上8点南京东路地铁站集合',
      time: '周三 10:00',
    },
    {
      id: 'msg_011_2',
      postId: 'post_011',
      sender: { id: 'user_018', nickName: '摄影新手', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user018' },
      content: '我只有手机，可以参加吗？',
      time: '周三 10:30',
    },
    {
      id: 'msg_011_3',
      postId: 'post_011',
      sender: { id: 'user_012', nickName: '摄影师阿杰', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user012' },
      content: '手机也可以，重要的是构图和眼光',
      time: '周三 10:35',
    },
    {
      id: 'msg_011_4',
      postId: 'post_011',
      sender: { id: 'user_001', nickName: '小明同学', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user001' },
      content: '记得带备用电池',
      time: '周一',
    },
    {
      id: 'msg_011_5',
      postId: 'post_011',
      sender: { id: 'user_018', nickName: '摄影新手', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user018' },
      content: '好的，充满电出发！',
      time: '周一',
    },
  ],
};

module.exports = {
  MOCK_USER,
  INITIAL_POSTS,
  CHAT_ITEMS_INITIATED,
  CHAT_ITEMS_JOINED,
  CHAT_MESSAGES,
};
